import { Comic } from '../interface/comic';

export const comics: Comic[] = [
  {
    id: 10020001,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Asilo Arkham (Edición deluxe) ',
    serie: 'BATMAN',
    precioRegular: 38.00,
    precioEspecial: 36.10,
    autores: ['Dave McKean', 'Grant Morrison'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: '¡La inolvidable novela gráfica en la que el Hombre Murciélago se ve obligado a enfrentarse a sus enemigos más letales y a sus miedos más profundos recibe el tratamiento Deluxe! Durante un aciago 1 de abril, los internos de Arkham logran hacerse con el control del legendario hospital psiquiátrico, secuestrando a los trabajadores del centro. Liderados por el Joker, los criminales más despiadados e inestables de Gotham City —Dos Caras, Killer Croc o el Sombrerero Loco, entre otros— exigen una única condición para liberar a los rehenes: que Batman les acompañe en tan siniestra morada.',
    isbn: '9788410203112',
    numeroDePaginas: 232,
    img: 'comics/batman/batman-asilo.webp'
  },
  {
    id: 10020002,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Año Uno (Grandes Novelas Gráficas de Batman)',
    serie: 'BATMAN',
    precioRegular: 20.50,
    precioEspecial: 19.48,
    autores: ['David Mazzucchelli', 'Frank Miller'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: 'Bruce Wayne ha vuelto a su ciudad natal después de un largo periplo por el mundo con una intención clara: que nadie sufra la tragedia que le destruyó la vida a él. Y lo cierto es que no va a faltarle trabajo, ya que Gotham City se ha convertido en un pozo de corrupción al que también acaba de llegar un policía llamado James Gordon que se convertirá en su principal aliado. Con guion del mismísimo Frank Miller y dibujo del maestro David Mazzucchelli, Batman: Año uno es el relato definitivo del origen de Batman y de sus inicios como defensor de Gotham City, pero también un estudio inolvidable de James Gordon como héroe incorruptible que lo tiene todo en contra.',
    isbn: '9788419972866',
    numeroDePaginas: 128,
    img: 'comics/batman/batman-anoUno.webp'
  },
  {
    id: 10020003,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Tortugas Ninja 03 (DC Pocket) (03 de 03)',
    serie: 'BATMAN',
    precioRegular: 9.95,
    precioEspecial: 9.45,
    autores: ['Freddie Williams II', 'James Tynion IV'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN', 'LAS TORTUGAS NINJA'],
    descripcion: 'Bruce Wayne, criado por el maestro Splinter, lucha contra el crimen junto a sus hermanos, cuatro ninjas que, en realidad, son tortugas mutantes. Sin embargo, el joven humano está teniendo sueños sobre una vida anterior y, cuando el cielo se tiñe de rojo, es un visitante de otra dimensión quien viene a resolver todas sus dudas. El guionista James Tynion IV y el dibujante Freddie E. Williams II, responsables de los anteriores volúmenes de Batman/Tortugas Ninja, nos cuentan la aventura compartida definitiva, todo un guiño a la historia del Universo DC que, además, con la participación especial de uno de sus creadores, Kevin Eastman.',
    isbn: '9788419920553',
    numeroDePaginas: 144,
    img: 'comics/batman/batman-tortugasNinja.webp'
  },
  {
    id: 10020004,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: 18/148',
    serie: 'BATMAN',
    precioRegular: 3.50,
    precioEspecial: 3.33,
    autores: ['Chip Zdarsky', 'Jorge Corona', 'Jorge Jiménez'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: '¡El Amanecer de DC sigue aquí! Tras los sucesos de La guerra de Gotham, Batman, aislado, lucha por frenar sus instintos más oscuros. Mientras, el Joker ha regresado a la ciudad y planea su siguiente golpe. ¿Será este el choque definitivo entre el Caballero Oscuro y el Príncipe Payaso del Crimen? ¡Un nuevo arco argumental del dúo dinámico formado por Chip Zdarsky y Jorge Jiménez!',
    isbn: '9788410330337',
    numeroDePaginas: 32,
    img: 'comics/batman/batman-18.png'

  },
  {
    id: 10020005,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Asilo Arkham - Purgatorio',
    serie: 'BATMAN',
    precioRegular: 24.00,
    precioEspecial: 22.80,
    autores: ['Dan Slott', 'Ryan Sook'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: 'Warren White, alias el Gran Tiburón Blanco, se las prometía muy felices. Alegó enajenación mental para librarse de una condena por fraude, pero su destino fue... ¡el Asilo Arkham! ¿Será capaz de convivir con elementos como el Joker? Y cuando alguien trate de echarle una mano, ¿tendrá intenciones sinceras o será una trampa? El guionista Dan Slott y el dibujante Ryan Sook presentan Asilo Arkham: Purgatorio, una historia que demuestra que, en Gotham City, ingresar en un centro psiquiátrico es aún peor que ir a una cárcel común y corriente.',
    isbn: '9788410134942',
    numeroDePaginas: 176,
    img: 'comics/batman/batman-purgatorio.webp'
  },
  {
    id: 10020006,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Tierra Uno 02 (DC Pocket) ',
    serie: 'BATMAN',
    precioRegular: 9.95,
    precioEspecial: 9.45,
    autores: ['Gary Frank', 'Geoff Johns'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: 'Se avecinan cambios en Gotham City. Entre la muerte del alcalde Oswald Cobblepot y la aparición de “Batman”, un nuevo amanecer arroja su luz sobre la ciudad, célebre por sus tinieblas y su corrupción. La nueva alcaldesa, Jessica Dent, y su hermano —el fiscal del distrito, Harvey Dent— se han unido al Caballero Oscuro y al detective Jim Gordon en su cruzada contra los criminales de Gotham. Pero surge una nueva amenaza... y le encanta jugar a los acertijos. Esta segunda entrega del bestseller de las listas del New York Times, Batman: Tierra Uno, vuelve a unir al guionista Geoff Johns y al dibujante Gary Frank para presentar ante los lectores a algunos de los más infames antagonistas del Hombre Murciélago... pero con cambios y giros inesperados que construyen una mitología tan novedosa como increíble.',
    isbn: '9788419733474',
    numeroDePaginas: 160,
    img: 'comics/batman/batman-tierraUno.webp'
  },
  {
    id: 10020007,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman: Asilo Arkham (DC Black Label Pocket)',
    serie: 'BATMAN',
    precioRegular: 9.95,
    precioEspecial: 9.45,
    autores: ['Dave McKean', 'Grant Morrison'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN'],
    descripcion: 'Durante un aciago 1 de abril, los internos de Arkham logran hacerse con el control del hospital psiquiátrico, secuestrando a los trabajadores del centro. Liderados por el Joker, los criminales más despiadados e inestables de Gotham City —Dos Caras, Killer Croc o el Sombrerero Loco, entre otros— exigen una única condición para liberar a los rehenes: que Batman les acompañe en tan siniestra morada.',
    isbn: '9788410609463',
    numeroDePaginas: 56,
    img: 'comics/batman/batman-asiloPocket.webp'
  },
  {
    id: 30010001,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman: India',
    serie: 'SPIDERMAN',
    precioRegular: 21.00,
    precioEspecial: 19.95,
    autores: ['Sharad Devarajan', 'Suresh Seetharaman', 'Jeevan J. Kang'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: '¡Por fin en castellano, el debut de Pavitr Prabhakar, uno de los protagonistas de "Universo Spiderman". Todo el mundo conoce la historia de Spiderman... pero ¿y si las cosas hubieran sucedido de otra manera? ¿Qué pasaría si no fuera un neoyorquino llamado Peter Parker, sino un adolescente indio llamado Pavitr Prabhakar quien fuera dotado con las habilidades de la araña?',
    isbn: '9788411504386',
    numeroDePaginas: 112,
    img: 'comics/spiderman/spiderman_india.webp'
  },
  {
    id: 10010001,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman 04: Mundos Mejores',
    serie: 'Superman-batman',
    precioRegular: 35.50,
    precioEspecial: 33.73,
    autores: ['Rafael Albuquerque', 'Carlo Barberi', 'Ed Benes', 'Ian Churchill', 'Matthew Clark', 'Shane Davis', 'Allan Goldman', 'Michael Green', 'Mike Johnson', 'Joe Kelly', 'Ed McGuinness', 'Rags Morales', 'Sean Murphy', 'Ryan Ottley', 'Andrew Robinson'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN'],
    descripcion: 'La llegada de Supergirl dejó la Tierra repleta de kryptonita, uno de los pocos puntos flacos de Superman, de ahí que sus aliados emprendan la tarea de localizarla toda, cosa que no será nada fácil. Además, nuestros protagonistas conocen a los entrañables miembros de la Liguita, sufren un traspaso de poderes y deben investigar un misterio relacionado con una pregunta imposible: ¿Y si Thomas Wayne hubiera conocido en persona a Jor-El? Este tomo recopila los números 44 a 56 de la colección, acompañados de material extra.',
    isbn: '9788416901470',
    numeroDePaginas: 384,
    img: 'comics/batman-superman/superman-batman-mundos_mejo.webp'
  },
  {
    id: 10010002,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman: los mejores del mundo - elemental',
    serie: 'Superman-batman',
    precioRegular: 18.00,
    precioEspecial: 17.10,
    autores: ['Dan Mora', 'Mark Waid'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN'],
    descripcion: 'Todo indica que el asesinato del magnate Simon Stagg ha sido obra de Rex Mason, más conocido como... ¡Metamorfo! Aunque estas páginas también revelen eso, pronto la trama se complica y señala a sospechosos menos obvios, entre ellos un científico loco con querencia por los androides e incluso cierto millonario gothamita que no necesita presentaciones. Este volumen recopila íntegramente Elemental, una ambiciosa aventura a escala épica que abarca cinco episodios de la colección americana.',
    isbn: '9788419972033',
    numeroDePaginas: 144,
    img: 'comics/batman-superman/superman-batman-los_mejores_del_mundo.webp'
  },
  {
    id: 10010003,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman y Wonder Woman: cronicas de la trinidad 01',
    serie: 'Superman-batman',
    precioRegular: 19.50,
    precioEspecial: 18.53,
    autores: ['Varios autores'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN', 'WONDER WOMAN'],
    descripcion: 'Este volumen recopila historias protagonizadas por Batman, Superman y Wonder Woman, abarcando números de Legends of the Dark Knight, Adventures of Superman, The Batman Chronicles y Sensation Comics Featuring Wonder Woman.',
    isbn: '9788416409440',
    numeroDePaginas: 192,
    img: 'comics/batman-superman/superman-batman-cronicas_trinidad.webp'
  },
  {
    id: 10010004,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman: los infectados-03',
    serie: 'Superman-batman',
    precioRegular: 21.50,
    precioEspecial: 20.43,
    autores: ['Jody Houser', 'Joshua Williamson', 'Robert Venditti', 'Mark Andreyko', 'Zoe Quinn'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN'],
    descripcion: 'El Batman Que Ríe se ha instalado en Gotham City, pero no es lo peor a lo que van a tener que enfrentarse Batman y Superman en este volumen. El retorcido villano venido del Multiverso Oscuro ha infectado a varios héroes y heroínas, todos de suma confianza para nuestros protagonistas, que ahora tienen nuevos poderes y el alma corrompida por las tinieblas. La saga ¿Quiénes son los Seis Secretos? concluye en este volumen.',
    isbn: '9788419279965',
    numeroDePaginas: 192,
    img: 'comics/batman-superman/superman-batman-los_infectados-02.webp'
  },
  {
    id: 10010005,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman: los infectados-03',
    serie: 'Superman-batman',
    precioRegular: 23.50,
    precioEspecial: 22.33,
    autores: ['David Marquez', 'Fernando Pasarín', 'Iñaki Miranda', 'Jack Herbert', 'Jody Houser', 'Joe Bennett', 'Joshua Williamson', 'Paul Jenkins', 'Rachael Stott', 'Robert Venditti'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN'],
    descripcion: 'Joshua Williamson y David Márquez concluyen la saga inaugural de la serie Batman/Superman con una visita a Wonder Woman, que no va a reaccionar bien cuando se entere de la identidad de una de esas víctimas del Hombre Murciélago Que Ríe. Este volumen incluye también historias protagonizadas por esos héroes ahora infectados, como Supergirl, Hawkman o el propio Gordon.',
    isbn: '9788419428417',
    numeroDePaginas: 208,
    img: 'comics/batman-superman/superman-batman-los_infectados-03.webp'
  },
  {
    id: 10010006,
    colecciones: ['UNIVERSO DC'],
    titulo: 'Batman/Superman: leyendas de los mejores del mundo',
    serie: 'Superman-batman',
    precioRegular: 16.95,
    precioEspecial: 16.10,
    autores: ['Walter Simonson'],
    editorial: 'ECC Ediciones',
    etiquetas: ['BATMAN','SUPERMAN'],
    descripcion: 'Una historia de almas perdidas y de redención. Un análisis de la luz y de la oscuridad. Y de lo que hay en medio. “Sigue habiendo algo muy incitador, incluso natural, en unir al Hombre de Acero y al Caballero Oscuro. Porque, pese al abismo que separa por naturaleza tanto sus habilidades como sus aventuras, los dos no dejan de representar polos opuestos del mismo espectro.”',
    isbn: '9788416255542',
    numeroDePaginas: 160,
    img: 'comics/batman-superman/superman-batman-leyendas_los_mejores_del_mundo.webp'
  },
  {
    id: 30010002,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman: Universo Spiderman (Marvel Must-Have)',
    serie: 'SPIDERMAN',
    precioRegular: 18.00,
    precioEspecial: 17.10,
    autores: ['Dan Slott', 'Olivier Coipel'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: '¡La saga que reúne a todos los Hombres Araña y Mujeres Araña que han existido jamás! Dan Slott (El Asombroso Spiderman) y Olivier Coipel (Dinastía de M) se unen para ofrecerte el mayor evento en la historia de Spiderman. Más peligroso que nunca, Morlun amenaza a todos los Hombres Araña que existen en el Multiverso, pero esta vez no está solo: tiene a la familia a su lado. ¡Todos los Spiderman que han existido están en peligro!',
    isbn: '9788411015141',
    numeroDePaginas: 184,
    img: 'comics/spiderman/spiderman_univ_must.webp'
  },
  {
    id: 30010003,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman 2099: Éxodo',
    serie: 'SPIDERMAN',
    precioRegular: 21.00,
    precioEspecial: 19.95,
    autores: ['Varios autores'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: 'Después de librar batallas a lo largo de la corriente temporal, Miguel O\'Hara, el Spiderman del año 2099, regresa finalmente a casa, para defender su presente... ¡y nuestro futuro! Descubre el siguiente reto para el Universo Marvel que vendrá, con las versiones de 2099 de Motorista Fantasma, el Soldado de Invierno, Loki, Los Nuevos Vengadores, La Viuda Negra, La Patrulla-X y El Duende Verde.',
    isbn: '9788411501675',
    numeroDePaginas: 184,
    img: 'comics/spiderman/spiderman_2099_exodo.webp'
  },
  {
    id: 30010004,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman VS Mysterio',
    serie: 'SPIDERMAN',
    precioRegular: 22.00,
    precioEspecial: 20.9,
    autores: ['Stan Lee'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: 'El amo de las ilusiones y de los efectos especiales salta a primer plano en Spider-Man: Homecoming, la nueva película del trepamuros. Para saberlo todo sobre él y estar preparado para el estreno, no te pierdas algunas de sus más interesantes aventuras.',
    isbn: '9788491679820',
    numeroDePaginas: 200,
    img: 'comics/spiderman/spiderman_mysterio.webp'
  },
  {
    id: 30010005,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman VS Tormeto (Marvel Must-Have)',
    serie: 'SPIDERMAN',
    precioRegular: 18.00,
    precioEspecial: 17.10,
    autores: ['Todd McFarlane'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: 'La sangre corre por la Gran Manzana. Spiderman se sumerge en la oscuridad mientras persigue a El Lagarto por las calles y alcantarillas de la ciudad, tratando de poner fin a la pulsión homicida que deja a su paso. Pero ¿quién está controlando a El Lagarto? ¿Es una respuesta que Spiderman está preparado para conocer? ¿O será tan impactante que hará que incluso el héroe más valiente cuestione su cordura? Descubre la primera historia dibujada y escrita por el famoso y comercial Todd McFarlane.',
    isbn: '9788411016407',
    numeroDePaginas: 136,
    img: 'comics/spiderman/spiderman_tormento.webp'
  },
  {
    id: 30010006,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman 2099: Génesis Oscura',
    serie: 'SPIDERMAN',
    precioRegular: 15.50,
    precioEspecial: 14.73,
    autores: ['Steve Orlando', 'Justin Mason'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: '¡Un futuro lleno de nuevos héroes y villanos! ¡Steve Orlando continúa su viaje a través del oscuro mañana de 2099! A medida que la sociedad comienza a desmoronarse, Spiderman 2099 necesitará toda la ayuda que pueda conseguir, pero ¿el público quiere siquiera que salve su vecindario o simplemente quieren ver arder este mundo retorcido?',
    isbn: '9788411509404',
    numeroDePaginas: 120,
    img: 'comics/spiderman/spiderman-2099_2.webp'
  },
  {
    id: 30010007,
    colecciones: ['MARVEL'],
    titulo: 'Spiderman Unlimited 01 (marvel Saga)',
    serie: 'SPIDERMAN',
    precioRegular: 16.50,
    precioEspecial: 15.68,
    autores: ['Brian Lynch', 'Jim Cheung', 'Kim Johnson', 'Matthew K. Manning', 'Mike Perkins', 'Paul Azaceta', 'Stuart Immonen', 'Joseph Goodrich', 'Adam Higgs', 'Tom McLaughlin', 'Allan Jacobsen', 'Martin Sweeney', 'Sheldon Allen', 'Scott Gimple', 'Bill Rosemann', 'C. P. Smith', 'Brandom Thomas'],
    editorial: 'Panini Comics',
    etiquetas: ['SPIDERMAN'],
    descripcion: 'Primer volumen de los dos que consta esta colección arácnida de mediados de la primera década de los 2000, parcialmente inédita en España, que reunió a algunos de los más prometedores guionistas del medio con los más fabulosos dibujantes. Catorce aventuras autoconclusivas del trepamuros entre las que se encuentran algunas auténticas joyas ocultas. ¡No descubrirás cuánto te gusta Spiderman Unlimited hasta que no la leas!',
    isbn: '9788411504829',
    numeroDePaginas: 184,
    img: 'comics/spiderman/spiderman-unlimited-marvel-saga.webp'
  },
  {
    id: 30020001,
    colecciones: ['MARVEL'],
    titulo: 'Daredevil 04: 1966-67',
    serie: 'OTROS-MARVEL',
    precioRegular: 13.95,
    precioEspecial: 13.25,
    autores: ['Gene Colan', 'John Romita Sr', 'Stan Lee'],
    editorial: 'Panini Comics',
    etiquetas: ['DAREDEVIL'],
    descripcion: 'Es más que un cómic: es una máquina del tiempo. El mundo del crimen ha señalado a Daredevil como su peor enemigo. Gladiador, El Merodeador Nocturno, El Búho... ¡todos quieren un pedazo del Hombre sin Miedo! Gene Colan sustituye a John Romita, para alzarse como el dibujante clave de la etapa clásica de Daredevil. Contiene los correos de los lectores de la edición original y la cronología que lo sitúa todo en contexto. ¡Biblioteca Marvel, como siempre y mejor que nunca! ¡No puedes perderte esta edición histórica!',
    isbn: '9788410513754',
    numeroDePaginas: 160,
    img: 'comics/Marvel/daredevil-4-biblioteca-marvel.webp'
  },
  {
    id: 30020002,
    colecciones: ['MARVEL'],
    titulo: 'La Patrulla X: 05',
    serie: 'OTROS-MARVEL',
    precioRegular: 13.95,
    precioEspecial: 13.25,
    autores: ['Roy Thomas', 'Werner Roth'],
    editorial: 'Panini Comics',
    etiquetas: ['Patrulla-X'],
    descripcion: 'Es más que un cómic: es una máquina del tiempo. ¡La plaga de La Langosta! ¡La amenaza de El Tigre! ¡El regreso de Mímico! ¡La presentación de Banshee, un mutante destinado a hacer historia! Contiene los correos de los lectores de la edición original y la cronología que lo sitúa todo en contexto. ¡Biblioteca Marvel, como siempre y mejor que nunca! ¡No puedes perderte esta edición histórica!',
    isbn: '9788410513747',
    numeroDePaginas: 160,
    img: 'comics/Marvel/patrulla-x-5-biblioteca-marvel.webp'
  },
  {
    id: 30020003,
    colecciones: ['MARVEL'],
    titulo: 'Capitán América: 08',
    serie: 'OTROS-MARVEL',
    precioRegular: 3.30,
    precioEspecial: 3.14,
    autores: ['Roy Thomas', 'Werner Roth'],
    editorial: 'Panini Comics',
    etiquetas: ['Capitan-América'],
    descripcion: 'Cuando Steve Rogers pensaba que la batalla contra Asmodeo estaba ganada, encuentra a una nueva aliada llamada Lyla, y descubre que la derrota de Asmodeo sólo ha servido para desatar una nueva amenaza. El comienzo de este nuevo arco llevará al Capi a lo largo de todo el Universo Marvel.',
    isbn: '977293851900800008',
    numeroDePaginas: 24,
    img: 'comics/Marvel/capitan-america-7-162-straczynski_1.webp'
  },
  {
    id: 30020004,
    colecciones: ['MARVEL'],
    titulo: 'Los Vengadores 12',
    serie: 'OTROS-MARVEL',
    precioRegular: 3.30,
    precioEspecial: 3.14,
    autores: ['Francesco Mortarino', 'Jed Mackay'],
    editorial: 'Panini Comics',
    etiquetas: ['LOS-VENGADORES'],
    descripcion: '¡Los Vengadores contra los Centinelas Stark! El contraataque de Orchis pone a Los Vengadores en desventaja después de que se descubra el verdadero alcance de los Centinelas Stark. ¿Podrán Los Héroes Más Poderosos de la Tierra enfrentarse a obstáculos imposibles?',
    isbn: '977293845100100012',
    numeroDePaginas: 24,
    img: 'comics/Marvel/los-vengadores-12.webp'
  },
  {
    id: 30020005,
    colecciones: ['MARVEL'],
    titulo: 'Lobezno 46',
    serie: 'OTROS-MARVEL',
    precioRegular: 8.95,
    precioEspecial: 8.50,
    autores: ['Francesco Mortarino', 'Jed Mackay'],
    editorial: 'Panini Comics',
    etiquetas: ['LOBEZNO'],
    descripcion: '¡Los Vengadores contra los Centinelas Stark! El contraataque de Orchis pone a Los Vengadores en desventaja después de que se descubra el verdadero alcance de los Centinelas Stark. ¿Podrán Los Héroes Más Poderosos de la Tierra enfrentarse a obstáculos imposibles?',
    isbn: '977293845100100012',
    numeroDePaginas: 24,
    img: 'comics/Marvel/lobezno-46.webp'
  },
  {
    id: 30020006,
    colecciones: ['MARVEL'],
    titulo: 'Patrulla-X 33',
    serie: 'OTROS-MARVEL',
    precioRegular: 5.50,
    precioEspecial: 5.23,
    autores: ['Bernard Chang', 'David Baldeón', 'Gerry Duggan', 'Javier Pina', 'Phil Noto'],
    editorial: 'Panini Comics',
    etiquetas: ['Patrulla-X'],
    descripcion: '¡Patrulla-X, reuníos! Si alguna vez hubo un momento para reunir a las tropas y luchar contra el enemigo, ¡es ahora! ¡Ponte al lado de los hombres y mujeres-X mientras se dirigen a su batalla final! ¡No pueden detenernos a todos! Además, el final de La Patrulla-X muerta.',
    isbn: '977000545800700156',
    numeroDePaginas: 48,
    img: 'comics/Marvel/patrulla-x-33.webp'
  },
  {
    id: 20010001,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 1 nº 01/72',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'En este primer volumen, conocemos a Naruto Uzumaki, un joven ninja con un sueño: convertirse en el Hokage, el líder de su aldea. Acompáñalo en sus primeras aventuras y descubre el mundo ninja que lo rodea.',
    isbn: '9781234567890',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto1.jpg'
  },
  {
    id: 20010002,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 1 nº 02/72',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'Naruto continúa su entrenamiento y se enfrenta a nuevos desafíos mientras forma su equipo con Sasuke Uchiha y Sakura Haruno. La serie de misiones y la lucha contra los enemigos se vuelven más intensas.',
    isbn: '9781234567891',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto2.jpg'
  },
  {
    id: 20010003,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 1 nº 03/72',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'La trama se intensifica con la llegada de nuevos enemigos y pruebas más difíciles para Naruto y su equipo. La historia avanza hacia conflictos que pondrán a prueba la fortaleza y el valor de nuestros héroes.',
    isbn: '9781234567892',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto3.jpg'
  },
  {
    id: 20010004,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 1 nº 04/72',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'La segunda parte de la serie trae nuevas aventuras y desafíos para Naruto, que ahora se enfrenta a enemigos aún más peligrosos y busca cumplir su destino como ninja.',
    isbn: '9781234567894',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto4.jpg'
  },
  {
    id: 20010073,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 2 nº 01/68',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'Las batallas se vuelven más intensas y las relaciones entre los personajes se complican. Naruto enfrenta grandes retos mientras su entrenamiento avanza hacia un nivel más alto.',
    isbn: '9781234567895',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto5.jpg'
  },
  {
    id: 20010074,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 2 nº 02/68',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'Las batallas se vuelven más intensas y las relaciones entre los personajes se complican. Naruto enfrenta grandes retos mientras su entrenamiento avanza hacia un nivel más alto.',
    isbn: '9781234567895',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto6.jpg'
  },
  {
    id: 20010075,
    colecciones: ['MANGA'],
    titulo: 'NARUTO parte 2 nº 03/68',
    serie: 'NARUTO',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Masashi Kishimoto'],
    editorial: 'Manga Shonen',
    etiquetas: ['NARUTO'],
    descripcion: 'La trama alcanza nuevos niveles de emoción con giros inesperados y revelaciones importantes. Naruto y sus amigos deben enfrentarse a los desafíos finales mientras buscan cumplir sus objetivos.',
    isbn: '9781234567896',
    numeroDePaginas: 192,
    img: 'comics/Naruto/naruto7.jpg'
  },
  {
    id: 20020001,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 1 nº01/124',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'En este primer volumen, conocemos a Goku, un joven con una cola de mono y una fuerza extraordinaria. Acompañado por Bulma, se embarca en la búsqueda de las siete Esferas del Dragón que conceden deseos.',
    isbn: '9782345678901',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db1.jpg'
  },
  {
    id: 20020002,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 1 nº02/124',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'Goku y Bulma continúan su búsqueda de las Esferas del Dragón y se enfrentan a nuevos retos y enemigos. La aventura se intensifica con la llegada de nuevos amigos y poderosos adversarios.',
    isbn: '9782345678902',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db2.jpg'
  },
  {
    id: 20020003,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 1 nº03/124',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'La búsqueda de las Esferas del Dragón lleva a Goku y sus amigos a nuevos lugares y enfrentamientos. Los desafíos aumentan y las habilidades de Goku se ponen a prueba como nunca antes.',
    isbn: '9782345678903',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db3.jpg'
  },
  {
    id: 20020125,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 2 nº01/108',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'La segunda parte de la serie empieza con Goku ya adulto, enfrentándose a nuevos y más poderosos enemigos. Las batallas se vuelven más intensas y los stakes son más altos que nunca.',
    isbn: '9782345678905',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db4.jpg'
  },
  {
    id: 20020126,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 2 nº02/108',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'Goku y sus amigos se enfrentan a nuevos desafíos y enemigos en su lucha por proteger la Tierra y las Esferas del Dragón. La acción y la emoción se intensifican en esta nueva entrega.',
    isbn: '9782345678906',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db5.jpg'
  },
  {
    id: 20020127,
    colecciones: ['MANGA'],
    titulo: 'DRAGON BALL parte 2 nº03/108',
    serie: 'DRAGON BALL',
    precioRegular: 10.00,
    precioEspecial: 9.00,
    autores: ['Akira Toriyama'],
    editorial: 'Manga Shonen',
    etiquetas: ['Dragon Ball'],
    descripcion: 'Goku y sus amigos se enfrentan a nuevos desafíos y enemigos en su lucha por proteger la Tierra y las Esferas del Dragón. La acción y la emoción se intensifican en esta nueva entrega.',
    isbn: '9782345678907',
    numeroDePaginas: 192,
    img: 'comics/dragonball/db6.jpg'
  }



];

